
title: My Resume
url: 'http://mikeaalv.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Yue Wu
tagline: Bioinformatics Researcher
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: yuewu_mike@163.com
github: mikeaalv
phone: TBD
website: TBD.com #do not add http://
linkedin: TBD
twitter: '@TBD'
